# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu1204--toey-recommend"
  config.vm.box_url = "http://dl.dropbox.com/u/1537815/precise64.box"

  #vb.gui = true
  config.vm.synced_folder "../", "/vagrant", mount_options: ['dmode=777', 'fmode=666']

  config.vm.network :private_network, ip: "192.168.111.228"
  config.vm.network :forwarded_port , host: 5000 , guest: 5000
  config.vm.network :forwarded_port , host: 80   , guest: 80
  config.vm.network :forwarded_port , host: 3606 , guest: 3606

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm" , :id , "--cpus"   , "2"]
    vb.customize ["modifyvm" , :id , "--memory" , "512"]
    vb.customize ["modifyvm" , :id , "--ioapic" , "on"]

    vb.customize ["modifyvm" , :id , "--natdnsproxy1"        , "off"]
    vb.customize ["modifyvm" , :id , "--natdnshostresolver1" , "on"]
    vb.customize ["modifyvm" , :id , "--natdnsproxy1"        , "on"]
  end

  ## provisioning with bootstrap script
  config.vm.provision :shell, :path => "bootstrap.sh"
  ## provisioning docker
  config.vm.provision :docker do |d|
    d.pull_images "centos"
  end  

end
